- name: Deploy WAR to Tomcat on Ubuntu
  hosts: all
  become: yes
  vars:
    tomcat_webapps: /var/lib/tomcat9/webapps

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Ensure Java is installed
      apt:
        name: openjdk-21-jdk
        state: present
        update_cache: yes

    - name: Install Tomcat 9
      apt:
        name: tomcat9
        state: latest

    - name: Download WAR from Nexus
      get_url:
        url: http://13.201.1.201:8081/repository/maven-releases/in/javahome/myweb/8.2.0/myweb-8.2.0.war
        dest: "{{ tomcat_webapps }}/app.war"

    - name: Restart Tomcat service
      service:
        name: tomcat9
        state: restarted
