- name: Deploy WAR to specific version of Tomcat on Ubuntu
  hosts: all
  become: yes
  vars:
    tomcat_version: "9.0.70"
    tomcat_user: "tomcat"
    tomcat_group: "tomcat"
    tomcat_install_dir: "/opt/tomcat"
    tomcat_webapps: "/opt/tomcat/webapps"
    tomcat_service_name: "tomcat"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure Java is installed
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Create tomcat group
      group:
        name: "{{ tomcat_group }}"

    - name: Create tomcat user
      user:
        name: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        shell: /bin/false
        create_home: no

    
    - name: Download Tomcat 9.0.70
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.70/bin/apache-tomcat-9.0.70.tar.gz
        dest: /tmp/apache-tomcat-9.0.70.tar.gz


    - name: Create Tomcat install directory
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Extract Tomcat
      unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ tomcat_install_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Set permissions for Tomcat
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        recurse: yes
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: Create systemd service for Tomcat
      copy:
        dest: /etc/systemd/system/{{ tomcat_service_name }}.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking

          User={{ tomcat_user }}
          Group={{ tomcat_group }}

          Environment=JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
          Environment=CATALINA_PID={{ tomcat_install_dir }}/temp/tomcat.pid
          Environment=CATALINA_HOME={{ tomcat_install_dir }}
          Environment=CATALINA_BASE={{ tomcat_install_dir }}
          Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
          Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'

          ExecStart={{ tomcat_install_dir }}/bin/startup.sh
          ExecStop={{ tomcat_install_dir }}/bin/shutdown.sh

          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start and enable Tomcat service
      service:
        name: "{{ tomcat_service_name }}"
        state: started
        enabled: yes

    - name: Download WAR from Nexus
      become: yes
      get_url:
        url: "http://13.201.1.201:8081/repository/maven-releases/in/javahome/myweb/8.2.0/myweb-8.2.0.war"
        dest: "{{ tomcat_webapps }}/app.war"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: '0777'

    - name: Restart Tomcat
      service:
        name: "{{ tomcat_service_name }}"
        state: restarted
